### ISSUE TITLE
Do we want to have pre-workshop reading lists? 

### ISSUE THREAD

**Issue by kjappelbaum** [MADICES/MADICES-2022#14]
I think it would be great if we could come up with a set of recommended blog posts/articles that participants can read in preparation for the breakout rooms. 

might lead to better discussions.

**Comment by ml-evs** [comment]
How about a more curated "awesome" list for interoperability like we did with https://github.com/neo-chem/awesome-chemical-data? I think it would be useful to get a list of the most popular technologies that people are using so that those unfamiliar can read up ahead of time (as well as blog posts and articles)

**Comment by kjappelbaum** [comment]
sounds good, let's create a new markdown file in this repo?

**Comment by kjappelbaum** [comment]
started one in [commit](https://github.com/MADICES/MADICES-2022/commit/825f62846c13f3a1c395281119919fe6d1a4afa8)

**Comment by ml-evs** [comment]
I guess we can close this now.
